### PR TITLE
[Maintenance] `canUserSubmitProposal` extracted to own component

### LINKED ISSUE #1501: `canUserSubmitProposal` not working correctly everywhere
Noticed that there are several additional requests coming out of `useSubmitProposal`. On a closer look there is a useEffect firing on mount to request this information depending on which DAO type and user is connected. But this doesn't need to happen everywhere that `useSubmitProposal` is used. The conditional needs to be updated so that the information isn't requested every render.

### PR DESCRIPTION
**Pull request by Da-Colon**
Draft till merged; Branched from #1495 

## Investigate Additional Request in `useAzoriosProposals` hook

Ill update the card but wasn't able to improve anything in this workflow. 
Updated #1457

## No issue, Investigate additional Requests in `useSubmitProposals`

There was logic for `canUserSubmitProposal` that was firing in a useEffect when this hook was mounted. Several places through the app mounted this hook but didn't use it. So I removed the logic into its own hook and replaced it through out the app. 
Closes #1501 

This update reduces the a few extra requests and also fixes permissions not properly being set when refreshing on proposal templates

## Testing.

There isn't really anything much to directly to test for this update. But you can ensure that refreshing on a Proposals Details screen or when creating a proposal, that permissions still load properly (like being able to create a proposal or template, button not disabled.)

### CODE REVIEW

File: src/hooks/DAO/loaders/governance/useERC20Claim.ts [hunk 1]
```diff
@@ -39,11 +45,20 @@ export function useERC20Claim() {
...
+      daoAddress + votesTokenContractAddress !== loadKey.current
+    ) {
+      loadKey.current = daoAddress + votesTokenContractAddress;
       loadTokenClaimContract();
     }
-  }, [loadTokenClaimContract, daoAddress]);
+    if (!daoAddress || !votesTokenContractAddress) {
+      loadKey.current = undefined;
+    }
+  }, [loadTokenClaimContract, daoAddress, votesTokenContractAddress]);
```
Comment (Da-Colon) [inline src/hooks/DAO/loaders/governance/useERC20Claim.ts:62]: added ref load key to prevent extra requests

File: src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx [hunk 2]
```diff
@@ -61,23 +60,13 @@ export function ManageDAOMenu({
...
 
-  useEffect(() => {
-    const loadCanUserCreateProposal = async () => {
-      if (safeAddress) {
-        setCanUserCreateProposal(await getCanUserCreateProposal(safeAddress));
-      }
-    };
-
-    loadCanUserCreateProposal();
-  }, [safeAddress, getCanUserCreateProposal]);
```
Comment (Da-Colon) [inline src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx:82]: This logic already happens inside the hook

File: src/hooks/DAO/proposal/useSubmitProposal.ts
Comment (Da-Colon) [inline src/hooks/DAO/proposal/useSubmitProposal.ts:1]: This logic wasn't being used within the 'useSubmitProposal itself, but it was causing this 'useEffect' to execute every where it is mounted causing extra requests

File: src/hooks/utils/useCanUserSubmitProposal.ts [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+    ],
+  );
+  useEffect(() => {
+    const loadCanUserCreateProposal = async () => {
+      setCanUserCreateProposal(await getCanUserCreateProposal());
+    };
+    if (canUserCreateProposal === undefined) {
+      loadCanUserCreateProposal();
+    }
+  }, [getCanUserCreateProposal, canUserCreateProposal, user]);
```
Comment (Da-Colon) [inline src/hooks/utils/useCanUserSubmitProposal.ts:102]: Some changes to logic here. added a conditional so that once setup it doesn't continue to request this data.

I also updated the return above ensuring that only when it is actually trying to check the permission a boolean is returned. 

The falsey setup conditional will just return undefined.

**Comment by adamgall** [comment]
@Da-Colon is the target branch for this PR correct? I see it's no longer in draft, but it doesn't target `develop`.

**Comment by adamgall** [comment]
Maybe it's just me, but DAOs don't load for me on this branch.

**Comment by Da-Colon** [comment]
> Maybe it's just me, but DAOs don't load for me on this branch.

weird. I just loaded one up on the preview.

**Comment by adamgall** [comment]
> > Maybe it's just me, but DAOs don't load for me on this branch.
> 
> weird. I just loaded one up on the preview.

Hm yes, you're right, me too. Must be something weird with my local dev env. I'll debug more on my side.

**Comment by adamgall** [comment]
@Da-Colon can you please create an issue and explain what needs fixin, to attach to this PR?

**Comment by Da-Colon** [comment]
@adamgall For testing. This PR mostly eliminates several of the 429s we were seeing in the console but Also one area where a bug is shown from the speed up is. 

If you pull up #1486 Go to any DAO (I did this with a multisig) and go to create a new proposal Templates. Once on the create screen refresh.

When you fill out the form, the button to submit the form will remain disabled. (It may be flaky and work but I got a pretty high occurance) (so you don't have to fill out the form everytime, you can also fork a template then refresh on that screen)

When you do the same on this PR you won't have that problem.

File: src/hooks/utils/useCanUserSubmitProposal.ts (hunk 3 above)
Comment (adamgall) [reply src/hooks/utils/useCanUserSubmitProposal.ts:102]: Does `user` still need to be part of this dependency array?

File: src/hooks/DAO/loaders/governance/useERC20Claim.ts (hunk 1 above)
Comment (adamgall) [reply src/hooks/DAO/loaders/governance/useERC20Claim.ts]: Looks like the changes to this file were reverted. Intentional?

File: src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx (hunk 2 above)
Comment (adamgall) [reply src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx:80]: Yes, I see. Thank you

File: src/hooks/utils/useMasterCopy.ts [hunk 4]
```diff
@@ -58,6 +58,11 @@ export function useMasterCopy() {
       const filter = contract.filters.ModuleProxyCreation(proxyAddress, null);
       return contract.queryFilter(filter).then(proxiesCreated => {
         if (proxiesCreated.length === 0) {
+          setValue(
+            CacheKeys.MASTER_COPY_PREFIX + proxyAddress,
+            constants.AddressZero,
+            CacheExpiry.ONE_WEEK,
+          );
```
Comment (adamgall) [inline src/hooks/utils/useMasterCopy.ts:65]: Would you mind commenting on these additions. What benefits do we get by adding this data to local storage cache?

**Review by adamgall — COMMENTED** [review]
Looking great @Da-Colon , i just have two comments/questions before giving an approval.

File: src/hooks/utils/useMasterCopy.ts (hunk 4 above)
Comment (Da-Colon) [reply src/hooks/utils/useMasterCopy.ts:66]: Add a comment to the code

File: src/hooks/utils/useCanUserSubmitProposal.ts (hunk 3 above)
Comment (adamgall) [reply src/hooks/utils/useCanUserSubmitProposal.ts]: I see it has been removed, cool

**Review by adamgall — APPROVED** [review]
