### PR TITLE
Fix search box crashing app on manual input

### LINKED ISSUE #1716: App crashes when manually typing address in Search Bar
recording

### PR DESCRIPTION
**Pull request by DarksightKellar**
Fixes #1716:

Screenshot 2024-05-09 at 16 15 58

Edit: And #1673 :
Screenshot 2024-05-09 at 16 20 38

### CODE REVIEW

File: src/utils/hierarchy.ts [hunk 1]
```diff
@@ -1,18 +1,7 @@
...
-  | 'address'
-  | 'parentAddress'
-  | 'name'
-  | 'snapshotENS'
-  | 'proposalTemplatesHash'
-  | 'hierarchy'
->;
-
-export const mapChildNodes = (dao: DAOQueryNode) => {
+export const mapChildNodes = (dao: DAO) => {
```
Comment (adamgall) [inline src/utils/hierarchy.ts:4]: Really trying to get rid of this code huh

**Review by adamgall — APPROVED** [review]
